### PR TITLE
Add support of aarch64

### PR DESCRIPTION
**Pull request by unkcpz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by unkcpz** [comment]
@conda-forge-admin, please rerender

**Comment by unkcpz** [comment]
Hi @tartansandal, thanks a lot for this great forge. I need this to support for my `aarch64` machine, but the build failed since the `conda-bash-completion` which is also maintained by you. Are you considering to also put that on conda-forge and having `aarch64` supported? Thanks!

**Comment by tartansandal** [comment]
Hi @unkcpz :wave: I'll definitely have a look at extending support to include `aarch64`. I am a little pressed for time at the moment, so I not get around to looking into this till next weekend. :smile:

**Comment by unkcpz** [comment]
@tartansandal Thanks a lot for looking at it. No hush on it 😄

**Comment by unkcpz** [comment]
Hi @tartansandal, any update on this? We may need this for one of our docker container builds to support arm64 (https://github.com/aiidalab/aiidalab-docker-stack/pull/372).

**Comment by tartansandal** [comment]
Sorry for the delay @unkcpz :pray:  I'm actually not entirely sure why `conda-bash-completion` is not being built for `aarch64`. The only arch we skip  is Windows. Maybe I need to trigger a rebuild somehow.

**Comment by unkcpz** [comment]
thanks @tartansandal. You mean https://github.com/tartansandal/conda-bash-completion correct? I am a bit confused that the repo seems not a standard conda-forge recipe? You need to trigger the rebuild by hand I assume.

**Comment by jucor** [comment]
If memory serves, there's a global file for condaforge that lists all
packages that support aarch64, where the package's name needs to be added.
I believe I did it for another repo.

Found it:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt

Uh, weird, I had already added it in commit
51bfbe23f4573712ed4fc5f6bc7c5f2e8f78266e .

Maybe remove it, then readd it, and wait a few hours?

**Comment by jucor** [comment]
You can also monitor where you are in the queue, and whether your package
has been "seen", here:
https://conda-forge.org/status/

I realised I did it for arm osx only, whereas this thread is about aarch,
so as a wild guess you might need to add the package to this other
migration file:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/arch_rebuild.txt

**Comment by jucor** [comment]
Source of info for the arm osx migration, from which I infer the steps for
aarch migration, is the first paragraph of this section:
https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock

**Comment by unkcpz** [comment]
Thanks @jucor. So I re-render the build of this PR and see if it works?

**Comment by jucor** [comment]
Not yet, I think you need to add the package's name to the arch migration file in conda-forge-pinning, then the udpate should be automatic but can take a little while -- so monitor the status page, to see if it is pending, done, or failed.

**Comment by jucor** [comment]
To be clearer: my experience from adding OSX support to conda-bash-completion via https://github.com/tartansandal/conda-bash-completion/issues/18 is that, upon adding the  package name to the right fine in conda-forge-pinning repo, a bot automatically made a PR in this current repo with the correct modifications to this feedstock repo. I did not have to do any manual modifications.
So you might want to try that :)

**Comment by unkcpz** [comment]
Okay thanks, I know how to add support to aarch64, we did that for other packages before. I just didn't find the correct feedstock where it is in https://github.com/conda-forge/conda-bash-completion-feedstock ;)
I open a PR to rebuild https://github.com/conda-forge/conda-bash-completion-feedstock/pull/7 Let's see if that works.

**Comment by tartansandal** [comment]
@jucor Thanks so much for the refresher course on updating the arch. Its been such a long time. :smile: :heart:

**Comment by jucor** [comment]
With pleasure! I'm referring to it from memory and reading my own PRs, so I hope I'm not saying too much bullsh*t 😂 Hope this helps!

**Comment by unkcpz** [comment]
@jucor Yes it is very helpful, I can not find the feedstock repo if I did not follow the link of your PR :smile:

**Comment by unkcpz** [comment]
@conda-forge-admin, please rerender

**Comment by tartansandal** [comment]
@unkcpz I just manually triggered a re-run of the failed check to kick things along.

**Comment by unkcpz** [comment]
@conda-forge-admin, please rerender

**Comment by tartansandal** [comment]
@unkcpz It looks like we'll have to wait for the conda-forge bots to build and distribute the new version before these checks will pass.

**Comment by unkcpz** [comment]
Maybe a rerender is required? I find the `conda-bash-completion` just has a new release published ( https://anaconda.org/conda-forge/conda-bash-completion after you retrigger it.)

**Comment by tartansandal** [comment]
> Maybe a rerender is required? 

There is nothing to rerender.  We may have to wait for all the mirrors to be updated so that Azure can find the new version.  To kick of a fresh test, click on "Details" in the above failed check, then click on "Re-run failed jobs".  I've just done this. Best not to do too often or you will run out of you Azure quota.

**Comment by tartansandal** [comment]
I'm off to bed now. I'll merge in the morning if the checks pass.

**Comment by unkcpz** [comment]
@conda-forge-admin, please rerender

**Comment by unkcpz** [comment]
Okay no problem, have a good evening. 

I don't have permission to trigger the build manually. I add myself to the recipe maintainer, I hope this is okay for you. 
I also did a re-trigger by force push, hope it works.

**Comment by unkcpz** [comment]
Everything is good now! :confetti_ball:

**Comment by tartansandal** [comment]
@unkcpz All done. Best of luck with your docker stack! :smile:

**Pull request merged**
